db:
  image: mysql
  expose:
    - "3306"
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: keypass
    MYSQL_DATABASE: keypass
    MYSQL_USER: keypass
    MYSQL_PASSWORD: keypass

keypass:
  build: .
  links:
    - db
  expose:
    - "7070"
    - "7071"
  ports:
    - "7170:7070"
    - "7171:7071"
  command: -dbhost db    

